baseURL = "https://blog.matheuscastiglioni.com.br/"
defaultContentLanguage = "pt-br"
disqusShortname = "blog-matheus"
enableRobotsTXT = true
googleAnalytics = "G-VCYVKDZ4SX"
languageCode = "pt-br"
paginate = 10
paginatePath = "pagina"
summaryLength = 25
theme = "blogmhc"
title = "Blog do Matheus Castiglioni"

[params]
    author = "Matheus Castiglioni"
    authorInfo = "Apaixonado pelo mundo dos códigos e um eterno estudante, gosto de aprender e saber um pouco de tudo, aquela curiosidade de saber como tudo funciona, tento compartilhar o máximo de conhecimentos adquiridos e ajudar todos aqueles que sou capaz."
    authorPicture = "/assets/img/matheus-castiglioni.jpg"
    description = "Blog sobre desenvolvimento, compartilhando algumas linguagens como css3, html5, javascript, java, php, android, etc..."
    keywords = "Desenvolvimento, desenvolvimento front-end, front-end, programação, css3, html5, javascript, java, php, adroid"
    twitter = "@mahenrique94"

[taxonomies]
    author = "autor"
    category = "categoria"
    tag = "tag"
